### ISSUE TITLE
Can you add tutorial on how to add a diffrent model and use original image as the init?

### ISSUE THREAD

**Issue by WalidAliAlfaid** [camenduru/AnimateDiff-colab#3]
please!!!

**Comment by camenduru** [comment]
![image](https://github.com/camenduru/AnimateDiff-colab/assets/54370274/62722530-57f9-4f00-8e92-0cc49e500e90)

just change this url with your model url

**Comment by WalidAliAlfaid** [comment]
i did i even changed everything eles for my added model, can you test it
